include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-kubo
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for kubo
LUCI_DEPENDS:=+kubo
LUCI_PKGARCH:=all

PKG_MAINTAINER:=foxxorcat <foxxorcat@foxmail.com>
PKG_LICENSE:=MIT

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
